name: CICD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install && npm install typescript -g
      - name: Generate Deployment Package
        run: zip -r secnd-backend-main.zip .
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'secnd-backend'
          environment_name: 'secnd-backend-env'
          version_label: ${{ github.sha }}
          region: ca-central-1
          deployment_package: secnd-backend-main.zip
