const mens_attributes = {
  "men_tops_T-Shirts": [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  men_tops_Hoodies: [
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  men_tops_Sweaters_default: [
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  men_tops_Sweaters_Cardigans: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  men_tops_Sweaters_Crewneck: [
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  men_tops_Sweaters_Turtleneck: [
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  men_tops_Sweaters_Sweatshirt: [
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  "men_tops_Sweaters_Zip-Up": [
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  men_tops_Shirts_default: [
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  men_tops_Shirts_Polo: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  men_tops_Shirts_Casual: [
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  men_tops_Shirts_Rugby: [
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  "men_tops_Shirts_Button-Up": [
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  men_tops_Jerseys: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Top length type",
    "Sport",
    "Condition",
    "Clothing features",
    "Sports logo",
  ],
  men_tops_Vests: [
    "Age group",
    "Care instructions",
    "Outerwear clothing features",
  ],
  men_bottoms_Jeans_default: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  men_bottoms_Jeans_Skinny: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  men_bottoms_Jeans_Slim: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  men_bottoms_Jeans_Straight: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  men_bottoms_Jeans_Bootcut: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  men_bottoms_Jeans_Relaxed: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  men_bottoms_Jeans_Oversized: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  men_bottoms_Jeans_Wide: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  men_bottoms_Sweatpants: [
    "Activity",
    "Waist rise",
    "Pants length type",
    "Activewear clothing features",
  ],
  men_bottoms_Trousers_default: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  men_bottoms_Trousers_Khakis: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  men_bottoms_Trousers_Cargos: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  men_bottoms_Trousers_Chinos: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  men_bottoms_Trousers_Corduroy: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  men_bottoms_Trousers_Dress: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  men_bottoms_Trousers_Linen: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  men_bottoms_Trousers_Leather: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  men_bottoms_Shorts_default: [
    "Age group",
    "Fit",
    "Waist rise",
    "Clothing features",
  ],
  men_bottoms_Shorts_Cargo: [
    "Age group",
    "Fit",
    "Waist rise",
    "Clothing features",
  ],
  men_bottoms_Shorts_Jean: [
    "Age group",
    "Fit",
    "Waist rise",
    "Clothing features",
  ],
  men_bottoms_Shorts_Jogger: [
    "Age group",
    "Fit",
    "Waist rise",
    "Clothing features",
  ],
  men_bottoms_Shorts_Chino: [
    "Age group",
    "Fit",
    "Waist rise",
    "Clothing features",
  ],
  men_bottoms_Shorts_Bermudas: [
    "Age group",
    "Fit",
    "Waist rise",
    "Clothing features",
  ],
  men_outerwear_Coats_default: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  men_outerwear_Coats_Heavy: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  men_outerwear_Coats_Puffer: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  men_outerwear_Coats_Rain: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  men_outerwear_Coats_Parkas: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  men_outerwear_Jackets_default: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  men_outerwear_Jackets_Bomber: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  men_outerwear_Jackets_Denim: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  men_outerwear_Jackets_Leather: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  men_outerwear_Jackets_Windbreaker: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  men_outerwear_Jackets_Varsity: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  men_outerwear_Jackets_Field: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  men_outerwear_Jackets_Track: [
    "Activity",
    "Sleeve length type",
    "Neckline",
    "Activewear clothing features",
  ],
  men_outerwear_Jackets_Trucker: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  men_suits_Suits_default: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  men_suits_Suits_Jacket: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  men_suits_Suits_Trousers: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  men_suits_Suits_Waistcoat: [
    "Age group",
    "Care instructions",
    "Outerwear clothing features",
  ],
  "men_suits_Suits_One-Piece": [
    "Sleeve length type",
    "Age group",
    "Swimwear features",
  ],
};

const womens_attributes = {
  "women_tops_T-Shirts": [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  women_tops_Hoodies: ["Activity", "Neckline", "Activewear clothing features"],
  women_tops_Sweaters_default: [
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  women_tops_Sweaters_Cardigans: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  women_tops_Sweaters_Crewneck: [
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  women_tops_Sweaters_Turtleneck: [
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  women_tops_Sweaters_Sweatshirt: [
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  "women_tops_Sweaters_Zip-Up": [
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  women_tops_Shirts_default: [
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  women_tops_Shirts_Polo: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  women_tops_Shirts_Rugby: [
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  women_tops_Shirts_Casual: [
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  "women_tops_Shirts_Button-Up": [
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  women_tops_Crop_Tops: [
    "Activity",
    "Sleeve length type",
    "Activewear clothing features",
  ],
  women_tops_Tank_Tops: [
    "Activity",
    "Sleeve length type",
    "Activewear clothing features",
  ],
  women_tops_Blouses: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Top length type",
    "Clothing features",
  ],
  women_bottoms_Jeans: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  women_bottoms_Sweatpants: [
    "Activity",
    "Waist rise",
    "Pants length type",
    "Activewear clothing features",
  ],
  women_bottoms_Trousers_default: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  women_bottoms_Trousers_Khakis: [
    "Fit",
    "Pants length type",
    "Care instructions",
    "Maternity clothing features",
  ],
  women_bottoms_Trousers_Cargos: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  women_bottoms_Trousers_Chinos: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  women_bottoms_Short_default: [
    "Age group",
    "Fit",
    "Waist rise",
    "Clothing features",
  ],
  women_bottoms_Short_Cargo: [
    "Age group",
    "Fit",
    "Waist rise",
    "Clothing features",
  ],
  women_bottoms_Short_Jean: [
    "Age group",
    "Fit",
    "Waist rise",
    "Clothing features",
  ],
  women_bottoms_Short_Jogger: [
    "Age group",
    "Fit",
    "Waist rise",
    "Clothing features",
  ],
  women_bottoms_Short_Chino: [
    "Age group",
    "Fit",
    "Waist rise",
    "Clothing features",
  ],
  women_bottoms_Short_Bermudas: [
    "Age group",
    "Fit",
    "Waist rise",
    "Clothing features",
  ],
  women_bottoms_Leggings: [
    "Age group",
    "Fit",
    "Waist rise",
    "Pants length type",
    "Clothing features",
  ],
  women_bottoms_Skirts: [
    "Fit",
    "Waist rise",
    "Skirt/Dress length type",
    "Clothing features",
  ],
  women_dresses_default: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Skirt/Dress length type",
    "Clothing features",
    "Dress occasion",
    "Dress style",
  ],
  women_dresses_Dresses_default: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Skirt/Dress length type",
    "Clothing features",
    "Dress occasion",
    "Dress style",
  ],
  women_outerwear_Coats_default: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  women_outerwear_Coats_Heavy: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  women_outerwear_Coats_Puffer: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  women_outerwear_Coats_Rain: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  women_outerwear_Coats_Parkas: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  women_outerwear_Jackets_default: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  women_outerwear_Jackets_Bomber: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  women_outerwear_Jackets_Denim: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  women_outerwear_Jackets_Leather: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  women_outerwear_Jackets_Windbreaker: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  women_outerwear_Jackets_Varsity: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  women_outerwear_Jackets_Field: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  women_outerwear_Jackets_Track: [
    "Activity",
    "Sleeve length type",
    "Neckline",
    "Activewear clothing features",
  ],
  women_outerwear_Jackets_Trucker: [
    "Sleeve length type",
    "Age group",
    "Neckline",
    "Care instructions",
    "Outerwear clothing features",
  ],
  onesies_default: [
    "Sleeve length type",
    "Age group",
    "Clothing features",
    "Target Gender",
    "One-piece Style",
    "Pants length type",
  ],
  onesies_Jumpsuits: ["Sleeve length type", "Age group", "Clothing features"],
  onesies_Rompers: ["Sleeve length type", "Age group", "Clothing features"],
};

const features = {
  "activewear-clothing-features": [
    {
      id: "gid://shopify/TaxonomyValue/22735",
      handle: "adjustable-waistband",
      displayName: "Adjustable Waistband",
    },
    {
      id: "gid://shopify/TaxonomyValue/22736",
      handle: "anti-chafing-design",
      displayName: "Anti-Chafing Design",
    },
    {
      id: "gid://shopify/TaxonomyValue/22737",
      handle: "anti-static-properties",
      displayName: "Anti-Static Properties",
    },
    {
      id: "gid://shopify/TaxonomyValue/22738",
      handle: "body-contouring-fit",
      displayName: "Body Contouring Fit",
    },
    {
      id: "gid://shopify/TaxonomyValue/22739",
      handle: "breathable-design",
      displayName: "Breathable Design",
    },
    {
      id: "gid://shopify/TaxonomyValue/22740",
      handle: "compression",
      displayName: "Compression",
    },
    {
      id: "gid://shopify/TaxonomyValue/22741",
      handle: "flatlock-seams",
      displayName: "Flatlock Seams",
    },
    {
      id: "gid://shopify/TaxonomyValue/22742",
      handle: "four-way-stretch",
      displayName: "Four-Way Stretch",
    },
    {
      id: "gid://shopify/TaxonomyValue/22743",
      handle: "hidden-pockets",
      displayName: "Hidden Pockets",
    },
    {
      id: "gid://shopify/TaxonomyValue/22744",
      handle: "high-visibility-accents",
      displayName: "High Visibility Accents",
    },
    {
      id: "gid://shopify/TaxonomyValue/22745",
      handle: "mesh-panels",
      displayName: "Mesh Panels",
    },
    {
      id: "gid://shopify/TaxonomyValue/22746",
      handle: "moisture-wicking",
      displayName: "Moisture Wicking",
    },
    {
      id: "gid://shopify/TaxonomyValue/22747",
      handle: "odor-resistant",
      displayName: "Odor Resistant",
    },
    {
      id: "gid://shopify/TaxonomyValue/22748",
      handle: "quick-drying",
      displayName: "Quick Drying",
    },
    {
      id: "gid://shopify/TaxonomyValue/22749",
      handle: "reflective",
      displayName: "Reflective",
    },
    {
      id: "gid://shopify/TaxonomyValue/22750",
      handle: "removable-padding",
      displayName: "Removable Padding",
    },
    {
      id: "gid://shopify/TaxonomyValue/22751",
      handle: "seamless",
      displayName: "Seamless",
    },
    {
      id: "gid://shopify/TaxonomyValue/22752",
      handle: "sweatproof-pockets",
      displayName: "Sweatproof Pockets",
    },
    {
      id: "gid://shopify/TaxonomyValue/22753",
      handle: "temperature-regulation",
      displayName: "Temperature Regulation",
    },
    {
      id: "gid://shopify/TaxonomyValue/22754",
      handle: "thumbholes",
      displayName: "Thumbholes",
    },
    {
      id: "gid://shopify/TaxonomyValue/22755",
      handle: "uv-protection",
      displayName: "UV Protection",
    },
    {
      id: "gid://shopify/TaxonomyValue/22756",
      handle: "vegan-friendly",
      displayName: "Vegan Friendly",
    },
    {
      id: "gid://shopify/TaxonomyValue/22757",
      handle: "ventilation",
      displayName: "Ventilation",
    },
    {
      id: "gid://shopify/TaxonomyValue/22758",
      handle: "waterproof-coating",
      displayName: "Waterproof Coating",
    },
    {
      id: "gid://shopify/TaxonomyValue/22759",
      handle: "other",
      displayName: "Other",
    },
  ],
  "care-instructions": [
    {
      id: "gid://shopify/TaxonomyValue/14942",
      handle: "dry-clean-only",
      displayName: "Dry Clean Only",
    },
    {
      id: "gid://shopify/TaxonomyValue/24715",
      handle: "dryer-safe",
      displayName: "Dryer Safe",
    },
    {
      id: "gid://shopify/TaxonomyValue/14943",
      handle: "hand-wash",
      displayName: "Hand Wash",
    },
    {
      id: "gid://shopify/TaxonomyValue/14944",
      handle: "ironing-instructions",
      displayName: "Ironing Instructions",
    },
    {
      id: "gid://shopify/TaxonomyValue/10542",
      handle: "machine-washable",
      displayName: "Machine Washable",
    },
    {
      id: "gid://shopify/TaxonomyValue/11409",
      handle: "tumble-dry",
      displayName: "Tumble Dry",
    },
    {
      id: "gid://shopify/TaxonomyValue/27281",
      handle: "other",
      displayName: "Other",
    },
  ],
  neckline: [
    {
      id: "gid://shopify/TaxonomyValue/6704",
      handle: "asymmetric",
      displayName: "Asymmetric",
    },
    {
      id: "gid://shopify/TaxonomyValue/6705",
      handle: "bardot",
      displayName: "Bardot",
    },
    {
      id: "gid://shopify/TaxonomyValue/6706",
      handle: "boat",
      displayName: "Boat",
    },
    {
      id: "gid://shopify/TaxonomyValue/6707",
      handle: "cowl",
      displayName: "Cowl",
    },
    {
      id: "gid://shopify/TaxonomyValue/6711",
      handle: "crew",
      displayName: "Crew",
    },
    {
      id: "gid://shopify/TaxonomyValue/6708",
      handle: "halter",
      displayName: "Halter",
    },
    {
      id: "gid://shopify/TaxonomyValue/6709",
      handle: "hooded",
      displayName: "Hooded",
    },
    {
      id: "gid://shopify/TaxonomyValue/6710",
      handle: "mandarin",
      displayName: "Mandarin",
    },
    {
      id: "gid://shopify/TaxonomyValue/6712",
      handle: "mock",
      displayName: "Mock",
    },
    {
      id: "gid://shopify/TaxonomyValue/6713",
      handle: "plunging",
      displayName: "Plunging",
    },
    {
      id: "gid://shopify/TaxonomyValue/17092",
      handle: "round",
      displayName: "Round",
    },
    {
      id: "gid://shopify/TaxonomyValue/4324",
      handle: "split",
      displayName: "Split",
    },
    {
      id: "gid://shopify/TaxonomyValue/17093",
      handle: "square",
      displayName: "Square",
    },
    {
      id: "gid://shopify/TaxonomyValue/6714",
      handle: "sweetheart",
      displayName: "Sweetheart",
    },
    {
      id: "gid://shopify/TaxonomyValue/6715",
      handle: "turtle",
      displayName: "Turtle",
    },
    {
      id: "gid://shopify/TaxonomyValue/390",
      handle: "v-neck",
      displayName: "V-Neck",
    },
    {
      id: "gid://shopify/TaxonomyValue/6716",
      handle: "wrap",
      displayName: "Wrap",
    },
    {
      id: "gid://shopify/TaxonomyValue/26413",
      handle: "other",
      displayName: "Other",
    },
  ],
  "age-group": [
    {
      id: "gid://shopify/TaxonomyValue/19404",
      handle: "0-6-months",
      displayName: "0-6 Months",
    },
    {
      id: "gid://shopify/TaxonomyValue/19405",
      handle: "6-12-months",
      displayName: "6-12 Months",
    },
    {
      id: "gid://shopify/TaxonomyValue/19406",
      handle: "1-2-years",
      displayName: "1-2 Years",
    },
    {
      id: "gid://shopify/TaxonomyValue/2403",
      handle: "adults",
      displayName: "Adults",
    },
    {
      id: "gid://shopify/TaxonomyValue/534",
      handle: "all-ages",
      displayName: "All Ages",
    },
    {
      id: "gid://shopify/TaxonomyValue/2974",
      handle: "babies",
      displayName: "Babies",
    },
    {
      id: "gid://shopify/TaxonomyValue/1515",
      handle: "kids",
      displayName: "Kids",
    },
    {
      id: "gid://shopify/TaxonomyValue/19952",
      handle: "newborn",
      displayName: "Newborn",
    },
    {
      id: "gid://shopify/TaxonomyValue/2404",
      handle: "teens",
      displayName: "Teens",
    },
    {
      id: "gid://shopify/TaxonomyValue/10090",
      handle: "toddlers",
      displayName: "Toddlers",
    },
    {
      id: "gid://shopify/TaxonomyValue/18291",
      handle: "universal",
      displayName: "Universal",
    },
    {
      id: "gid://shopify/TaxonomyValue/26412",
      handle: "other",
      displayName: "Other",
    },
  ],
  activity: [
    {
      id: "gid://shopify/TaxonomyValue/104",
      handle: "aerobics",
      displayName: "Aerobics",
    },
    {
      id: "gid://shopify/TaxonomyValue/97",
      handle: "aikido",
      displayName: "Aikido",
    },
    {
      id: "gid://shopify/TaxonomyValue/90",
      handle: "air-hockey",
      displayName: "Air Hockey",
    },
    {
      id: "gid://shopify/TaxonomyValue/21211",
      handle: "australian-football",
      displayName: "Australian Football",
    },
    {
      id: "gid://shopify/TaxonomyValue/21212",
      handle: "badminton",
      displayName: "Badminton",
    },
    {
      id: "gid://shopify/TaxonomyValue/105",
      handle: "ballet",
      displayName: "Ballet",
    },
    {
      id: "gid://shopify/TaxonomyValue/69",
      handle: "baseball",
      displayName: "Baseball",
    },
    {
      id: "gid://shopify/TaxonomyValue/71",
      handle: "basketball",
      displayName: "Basketball",
    },
    {
      id: "gid://shopify/TaxonomyValue/72",
      handle: "boxing",
      displayName: "Boxing",
    },
    {
      id: "gid://shopify/TaxonomyValue/94",
      handle: "brazilian-jiu-jitsu",
      displayName: "Brazilian Jiu-Jitsu",
    },
    {
      id: "gid://shopify/TaxonomyValue/17704",
      handle: "car-racing",
      displayName: "Car Racing",
    },
    {
      id: "gid://shopify/TaxonomyValue/73",
      handle: "cheerleading",
      displayName: "Cheerleading",
    },
    {
      id: "gid://shopify/TaxonomyValue/99",
      handle: "climbing",
      displayName: "Climbing",
    },
    {
      id: "gid://shopify/TaxonomyValue/74",
      handle: "cricket",
      displayName: "Cricket",
    },
    {
      id: "gid://shopify/TaxonomyValue/100",
      handle: "cycling",
      displayName: "Cycling",
    },
    {
      id: "gid://shopify/TaxonomyValue/75",
      handle: "dancing",
      displayName: "Dancing",
    },
    {
      id: "gid://shopify/TaxonomyValue/98",
      handle: "darts",
      displayName: "Darts",
    },
    {
      id: "gid://shopify/TaxonomyValue/76",
      handle: "field-hockey",
      displayName: "Field Hockey",
    },
    {
      id: "gid://shopify/TaxonomyValue/101",
      handle: "fishing",
      displayName: "Fishing",
    },
    {
      id: "gid://shopify/TaxonomyValue/21213",
      handle: "floorball",
      displayName: "Floorball",
    },
    {
      id: "gid://shopify/TaxonomyValue/1348",
      handle: "football",
      displayName: "Football",
    },
    {
      id: "gid://shopify/TaxonomyValue/21214",
      handle: "futsal",
      displayName: "Futsal",
    },
    {
      id: "gid://shopify/TaxonomyValue/21215",
      handle: "gaelic-football",
      displayName: "Gaelic Football",
    },
    {
      id: "gid://shopify/TaxonomyValue/102",
      handle: "golf",
      displayName: "Golf",
    },
    {
      id: "gid://shopify/TaxonomyValue/79",
      handle: "gymnastics",
      displayName: "Gymnastics",
    },
    {
      id: "gid://shopify/TaxonomyValue/84",
      handle: "handball",
      displayName: "Handball",
    },
    {
      id: "gid://shopify/TaxonomyValue/21315",
      handle: "hiking",
      displayName: "Hiking",
    },
    {
      id: "gid://shopify/TaxonomyValue/78",
      handle: "hockey",
      displayName: "Hockey",
    },
    {
      id: "gid://shopify/TaxonomyValue/106",
      handle: "horse-riding",
      displayName: "Horse Riding",
    },
    {
      id: "gid://shopify/TaxonomyValue/103",
      handle: "hunting",
      displayName: "Hunting",
    },
    {
      id: "gid://shopify/TaxonomyValue/21216",
      handle: "hurling",
      displayName: "Hurling",
    },
    {
      id: "gid://shopify/TaxonomyValue/21217",
      handle: "ice-hockey",
      displayName: "Ice Hockey",
    },
    {
      id: "gid://shopify/TaxonomyValue/21247",
      handle: "inline-skating",
      displayName: "Inline Skating",
    },
    {
      id: "gid://shopify/TaxonomyValue/93",
      handle: "judo",
      displayName: "Judo",
    },
    {
      id: "gid://shopify/TaxonomyValue/91",
      handle: "karate",
      displayName: "Karate",
    },
    {
      id: "gid://shopify/TaxonomyValue/21251",
      handle: "kickboxing",
      displayName: "Kickboxing",
    },
    {
      id: "gid://shopify/TaxonomyValue/96",
      handle: "krav-maga",
      displayName: "Krav Maga",
    },
    {
      id: "gid://shopify/TaxonomyValue/77",
      handle: "lacrosse",
      displayName: "Lacrosse",
    },
    {
      id: "gid://shopify/TaxonomyValue/21252",
      handle: "mixed-martial-arts-mma",
      displayName: "Mixed Martial Arts (MMA)",
    },
    {
      id: "gid://shopify/TaxonomyValue/1397",
      handle: "motorcycling",
      displayName: "Motorcycling",
    },
    {
      id: "gid://shopify/TaxonomyValue/95",
      handle: "muay-thai",
      displayName: "Muay Thai",
    },
    {
      id: "gid://shopify/TaxonomyValue/107",
      handle: "netball",
      displayName: "Netball",
    },
    {
      id: "gid://shopify/TaxonomyValue/108",
      handle: "padel",
      displayName: "Padel",
    },
    {
      id: "gid://shopify/TaxonomyValue/89",
      handle: "pilates",
      displayName: "Pilates",
    },
    {
      id: "gid://shopify/TaxonomyValue/80",
      handle: "racquetball",
      displayName: "Racquetball",
    },
    {
      id: "gid://shopify/TaxonomyValue/21248",
      handle: "rounders",
      displayName: "Rounders",
    },
    {
      id: "gid://shopify/TaxonomyValue/82",
      handle: "rugby",
      displayName: "Rugby",
    },
    {
      id: "gid://shopify/TaxonomyValue/428",
      handle: "running",
      displayName: "Running",
    },
    {
      id: "gid://shopify/TaxonomyValue/24714",
      handle: "skateboarding",
      displayName: "Skateboarding",
    },
    {
      id: "gid://shopify/TaxonomyValue/21516",
      handle: "skiing",
      displayName: "Skiing",
    },
    {
      id: "gid://shopify/TaxonomyValue/21527",
      handle: "snowboarding",
      displayName: "Snowboarding",
    },
    {
      id: "gid://shopify/TaxonomyValue/83",
      handle: "soccer",
      displayName: "Soccer",
    },
    {
      id: "gid://shopify/TaxonomyValue/70",
      handle: "softball",
      displayName: "Softball",
    },
    {
      id: "gid://shopify/TaxonomyValue/81",
      handle: "squash",
      displayName: "Squash",
    },
    {
      id: "gid://shopify/TaxonomyValue/92",
      handle: "taekwondo",
      displayName: "Taekwondo",
    },
    {
      id: "gid://shopify/TaxonomyValue/21249",
      handle: "team-handball",
      displayName: "Team Handball",
    },
    {
      id: "gid://shopify/TaxonomyValue/85",
      handle: "tennis",
      displayName: "Tennis",
    },
    {
      id: "gid://shopify/TaxonomyValue/21250",
      handle: "track-field",
      displayName: "Track & Field",
    },
    {
      id: "gid://shopify/TaxonomyValue/21218",
      handle: "ultimate-frisbee",
      displayName: "Ultimate Frisbee",
    },
    {
      id: "gid://shopify/TaxonomyValue/21253",
      handle: "universal",
      displayName: "Universal",
    },
    {
      id: "gid://shopify/TaxonomyValue/86",
      handle: "volleyball",
      displayName: "Volleyball",
    },
    {
      id: "gid://shopify/TaxonomyValue/21219",
      handle: "water-polo",
      displayName: "Water Polo",
    },
    {
      id: "gid://shopify/TaxonomyValue/87",
      handle: "wrestling",
      displayName: "Wrestling",
    },
    {
      id: "gid://shopify/TaxonomyValue/88",
      handle: "yoga",
      displayName: "Yoga",
    },
    {
      id: "gid://shopify/TaxonomyValue/17085",
      handle: "other",
      displayName: "Other",
    },
  ],
  "sleeve-length-type": [
    {
      id: "gid://shopify/TaxonomyValue/1405",
      handle: "3-4",
      displayName: "3/4",
    },
    {
      id: "gid://shopify/TaxonomyValue/1407",
      handle: "cap",
      displayName: "Cap",
    },
    {
      id: "gid://shopify/TaxonomyValue/17094",
      handle: "long",
      displayName: "Long",
    },
    {
      id: "gid://shopify/TaxonomyValue/169",
      handle: "short",
      displayName: "Short",
    },
    {
      id: "gid://shopify/TaxonomyValue/174",
      handle: "sleeveless",
      displayName: "Sleeveless",
    },
    {
      id: "gid://shopify/TaxonomyValue/176",
      handle: "spaghetti-strap",
      displayName: "Spaghetti Strap",
    },
    {
      id: "gid://shopify/TaxonomyValue/177",
      handle: "strapless",
      displayName: "Strapless",
    },
    {
      id: "gid://shopify/TaxonomyValue/26410",
      handle: "other",
      displayName: "Other",
    },
  ],
  "waist-rise": [
    {
      id: "gid://shopify/TaxonomyValue/1376",
      handle: "high",
      displayName: "High",
    },
    {
      id: "gid://shopify/TaxonomyValue/1364",
      handle: "low",
      displayName: "Low",
    },
    {
      id: "gid://shopify/TaxonomyValue/1365",
      handle: "mid",
      displayName: "Mid",
    },
    {
      id: "gid://shopify/TaxonomyValue/26415",
      handle: "other",
      displayName: "Other",
    },
  ],
  fit: [
    {
      id: "gid://shopify/TaxonomyValue/6719",
      handle: "boyfriend",
      displayName: "Boyfriend",
    },
    {
      id: "gid://shopify/TaxonomyValue/6720",
      handle: "mom",
      displayName: "Mom",
    },
    {
      id: "gid://shopify/TaxonomyValue/419",
      handle: "skinny-leg",
      displayName: "Skinny Leg",
    },
    {
      id: "gid://shopify/TaxonomyValue/6718",
      handle: "slim",
      displayName: "Slim",
    },
    {
      id: "gid://shopify/TaxonomyValue/420",
      handle: "straight-leg",
      displayName: "Straight Leg",
    },
    {
      id: "gid://shopify/TaxonomyValue/418",
      handle: "tapered-leg",
      displayName: "Tapered Leg",
    },
    {
      id: "gid://shopify/TaxonomyValue/3102",
      handle: "wide",
      displayName: "Wide",
    },
    {
      id: "gid://shopify/TaxonomyValue/26414",
      handle: "other",
      displayName: "Other",
    },
  ],
  "pants-length-type": [
    {
      id: "gid://shopify/TaxonomyValue/230",
      handle: "above-the-knee",
      displayName: "Above the Knee",
    },
    {
      id: "gid://shopify/TaxonomyValue/231",
      handle: "capri",
      displayName: "Capri",
    },
    {
      id: "gid://shopify/TaxonomyValue/232",
      handle: "cropped",
      displayName: "Cropped",
    },
    {
      id: "gid://shopify/TaxonomyValue/233",
      handle: "footed",
      displayName: "Footed",
    },
    {
      id: "gid://shopify/TaxonomyValue/166",
      handle: "knee",
      displayName: "Knee",
    },
    {
      id: "gid://shopify/TaxonomyValue/1406",
      handle: "long",
      displayName: "Long",
    },
    {
      id: "gid://shopify/TaxonomyValue/26430",
      handle: "other",
      displayName: "Other",
    },
  ],
  "dress-occasion": [
    {
      id: "gid://shopify/TaxonomyValue/24716",
      handle: "birthday",
      displayName: "Birthday",
    },
    {
      id: "gid://shopify/TaxonomyValue/24717",
      handle: "casual",
      displayName: "Casual",
    },
    {
      id: "gid://shopify/TaxonomyValue/24718",
      handle: "dance",
      displayName: "Dance",
    },
    {
      id: "gid://shopify/TaxonomyValue/24719",
      handle: "everyday",
      displayName: "Everyday",
    },
    {
      id: "gid://shopify/TaxonomyValue/24720",
      handle: "formal",
      displayName: "Formal",
    },
    {
      id: "gid://shopify/TaxonomyValue/24721",
      handle: "holiday",
      displayName: "Holiday",
    },
    {
      id: "gid://shopify/TaxonomyValue/24722",
      handle: "pageant",
      displayName: "Pageant",
    },
    {
      id: "gid://shopify/TaxonomyValue/24723",
      handle: "party",
      displayName: "Party",
    },
    {
      id: "gid://shopify/TaxonomyValue/24724",
      handle: "portrait",
      displayName: "Portrait",
    },
    {
      id: "gid://shopify/TaxonomyValue/24725",
      handle: "religious-ceremony",
      displayName: "Religious Ceremony",
    },
    {
      id: "gid://shopify/TaxonomyValue/24726",
      handle: "school",
      displayName: "School",
    },
    {
      id: "gid://shopify/TaxonomyValue/24727",
      handle: "wedding",
      displayName: "Wedding",
    },
    {
      id: "gid://shopify/TaxonomyValue/27925",
      handle: "other",
      displayName: "Other",
    },
  ],
  "dress-style": [
    {
      id: "gid://shopify/TaxonomyValue/24728",
      handle: "a-line",
      displayName: "A-Line",
    },
    {
      id: "gid://shopify/TaxonomyValue/24729",
      handle: "babydoll",
      displayName: "Babydoll",
    },
    {
      id: "gid://shopify/TaxonomyValue/24730",
      handle: "blouson",
      displayName: "Blouson",
    },
    {
      id: "gid://shopify/TaxonomyValue/24731",
      handle: "caftan",
      displayName: "Caftan",
    },
    {
      id: "gid://shopify/TaxonomyValue/24732",
      handle: "drop-waist",
      displayName: "Drop Waist",
    },
    {
      id: "gid://shopify/TaxonomyValue/24733",
      handle: "empire-waist",
      displayName: "Empire Waist",
    },
    {
      id: "gid://shopify/TaxonomyValue/24734",
      handle: "flared",
      displayName: "Flared",
    },
    {
      id: "gid://shopify/TaxonomyValue/24735",
      handle: "gown",
      displayName: "Gown",
    },
    {
      id: "gid://shopify/TaxonomyValue/24736",
      handle: "jacket",
      displayName: "Jacket",
    },
    {
      id: "gid://shopify/TaxonomyValue/24737",
      handle: "mermaid",
      displayName: "Mermaid",
    },
    {
      id: "gid://shopify/TaxonomyValue/24738",
      handle: "pencil",
      displayName: "Pencil",
    },
    {
      id: "gid://shopify/TaxonomyValue/24739",
      handle: "peplum",
      displayName: "Peplum",
    },
    {
      id: "gid://shopify/TaxonomyValue/24740",
      handle: "sheath",
      displayName: "Sheath",
    },
    {
      id: "gid://shopify/TaxonomyValue/24741",
      handle: "shift",
      displayName: "Shift",
    },
    {
      id: "gid://shopify/TaxonomyValue/24742",
      handle: "shirt",
      displayName: "Shirt",
    },
    {
      id: "gid://shopify/TaxonomyValue/24743",
      handle: "skater",
      displayName: "Skater",
    },
    {
      id: "gid://shopify/TaxonomyValue/24744",
      handle: "slip",
      displayName: "Slip",
    },
    {
      id: "gid://shopify/TaxonomyValue/24745",
      handle: "sweater",
      displayName: "Sweater",
    },
    {
      id: "gid://shopify/TaxonomyValue/24746",
      handle: "tank",
      displayName: "Tank",
    },
    {
      id: "gid://shopify/TaxonomyValue/24747",
      handle: "trumpet",
      displayName: "Trumpet",
    },
    {
      id: "gid://shopify/TaxonomyValue/24748",
      handle: "wrap",
      displayName: "Wrap",
    },
    {
      id: "gid://shopify/TaxonomyValue/24749",
      handle: "other",
      displayName: "Other",
    },
  ],
  "outerwear-clothing-features": [
    {
      id: "gid://shopify/TaxonomyValue/22775",
      handle: "breathable-design",
      displayName: "Breathable Design",
    },
    {
      id: "gid://shopify/TaxonomyValue/22776",
      handle: "hooded",
      displayNme: "Hooded",
    },
    {
      id: "gid://shopify/TaxonomyValue/22777",
      handle: "hypoallergenic",
      displayName: "Hypoallergenic",
    },
    {
      id: "gid://shopify/TaxonomyValue/22778",
      handle: "insulated",
      displayName: "Insulated",
    },
    {
      id: "gid://shopify/TaxonomyValue/22779",
      handle: "lightweight",
      displayName: "Lightweight",
    },
    {
      id: "gid://shopify/TaxonomyValue/22780",
      handle: "pockets",
      displayName: "Pockets",
    },
    {
      id: "gid://shopify/TaxonomyValue/22781",
      handle: "quick-drying",
      displayName: "Quick Drying",
    },
    {
      id: "gid://shopify/TaxonomyValue/22782",
      handle: "thermal",
      displayName: "Thermal",
    },
    {
      id: "gid://shopify/TaxonomyValue/22783",
      handle: "uv-protection",
      displayName: "UV Protection",
    },
    {
      id: "gid://shopify/TaxonomyValue/22784",
      handle: "waterproof",
      displayName: "Waterproof",
    },
    {
      id: "gid://shopify/TaxonomyValue/22785",
      handle: "windproof",
      displayName: "Windproof",
    },
    {
      id: "gid://shopify/TaxonomyValue/22786",
      handle: "wrinkle-resistant",
      displayName: "Wrinkle Resistant",
    },
    {
      id: "gid://shopify/TaxonomyValue/27747",
      handle: "other",
      displayName: "Other",
    },
  ],
  "clothing-features": [
    {
      id: "gid://shopify/TaxonomyValue/22804",
      handle: "hypoallergenic",
      displayName: "Hypoallergenic",
    },
    {
      id: "gid://shopify/TaxonomyValue/22805",
      handle: "insulated",
      displayName: "Insulated",
    },
    {
      id: "gid://shopify/TaxonomyValue/22806",
      handle: "moisture-wicking",
      displayName: "Moisture Wicking",
    },
    {
      id: "gid://shopify/TaxonomyValue/22807",
      handle: "quick-drying",
      displayName: "Quick Drying",
    },
    {
      id: "gid://shopify/TaxonomyValue/22808",
      handle: "reversible",
      displayName: "Reversible",
    },
    {
      id: "gid://shopify/TaxonomyValue/22809",
      handle: "stretchable",
      displayName: "Stretchable",
    },
    {
      id: "gid://shopify/TaxonomyValue/22810",
      handle: "uv-protection",
      displayName: "UV Protection",
    },
    {
      id: "gid://shopify/TaxonomyValue/22811",
      handle: "vegan-friendly",
      displayName: "Vegan Friendly",
    },
    {
      id: "gid://shopify/TaxonomyValue/22812",
      handle: "water-resistant",
      displayName: "Water Resistant",
    },
    {
      id: "gid://shopify/TaxonomyValue/22813",
      handle: "windproof",
      displayName: "Windproof",
    },
    {
      id: "gid://shopify/TaxonomyValue/22814",
      handle: "wrinkle-resistant",
      displayName: "Wrinkle Resistant",
    },
    {
      id: "gid://shopify/TaxonomyValue/27750",
      handle: "other",
      displayName: "Other",
    },
  ],
  "skirt-dress-length-type": [
    {
      id: "gid://shopify/TaxonomyValue/21911",
      handle: "knee",
      displayName: "Knee",
    },
    {
      id: "gid://shopify/TaxonomyValue/167",
      handle: "maxi",
      displayName: "Maxi",
    },
    {
      id: "gid://shopify/TaxonomyValue/168",
      handle: "midi",
      displayName: "Midi",
    },
    {
      id: "gid://shopify/TaxonomyValue/21913",
      handle: "mini",
      displayName: "Mini",
    },
    {
      id: "gid://shopify/TaxonomyValue/21912",
      handle: "short",
      displayName: "Short",
    },
  ],
  "top-length-type": [
    {
      id: "gid://shopify/TaxonomyValue/339",
      handle: "bodysuit",
      displayName: "Bodysuit",
    },
    {
      id: "gid://shopify/TaxonomyValue/165",
      handle: "crop-top",
      displayName: "Crop Top",
    },
    {
      id: "gid://shopify/TaxonomyValue/17110",
      handle: "long",
      displayName: "Long",
    },
    {
      id: "gid://shopify/TaxonomyValue/17111",
      handle: "medium",
      displayName: "Medium",
    },
    {
      id: "gid://shopify/TaxonomyValue/26434",
      handle: "other",
      displayName: "Other",
    },
  ],
  "maternity-clothing-features": [
    {
      id: "gid://shopify/TaxonomyValue/22816",
      handle: "adjustable-strap",
      displayName: "Adjustable Strap",
    },
    {
      id: "gid://shopify/TaxonomyValue/22817",
      handle: "breathable-design",
      displayName: "Breathable Design",
    },
    {
      id: "gid://shopify/TaxonomyValue/22818",
      handle: "chlorine-resistant",
      displayName: "Chlorine Resistant",
    },
    {
      id: "gid://shopify/TaxonomyValue/22819",
      handle: "elastic-waistband",
      displayName: "Elastic Waistband",
    },
    {
      id: "gid://shopify/TaxonomyValue/22820",
      handle: "flattering-silhouette",
      displayName: "Flattering Silhouette",
    },
    {
      id: "gid://shopify/TaxonomyValue/22821",
      handle: "flexible",
      displayName: "Flexible",
    },
    {
      id: "gid://shopify/TaxonomyValue/22822",
      handle: "lightweight",
      displayName: "Lightweight",
    },
    {
      id: "gid://shopify/TaxonomyValue/22823",
      handle: "quick-drying",
      displayName: "Quick Drying",
    },
    {
      id: "gid://shopify/TaxonomyValue/22824",
      handle: "room-for-belly-growth",
      displayName: "Room for Belly Growth",
    },
    {
      id: "gid://shopify/TaxonomyValue/22825",
      handle: "supportive-cups",
      displayName: "Supportive Cups",
    },
    {
      id: "gid://shopify/TaxonomyValue/22826",
      handle: "upf-sun-protection",
      displayName: "UPF Sun Protection",
    },
    {
      id: "gid://shopify/TaxonomyValue/22827",
      handle: "vegan-friendly",
      displayName: "Vegan Friendly",
    },
    {
      id: "gid://shopify/TaxonomyValue/27751",
      handle: "other",
      displayName: "Other",
    },
  ],
  "one-piece-style": [
    {
      id: "gid://shopify/TaxonomyValue/24760",
      handle: "bodysuit",
      displayName: "Bodysuit",
    },
    {
      id: "gid://shopify/TaxonomyValue/24761",
      handle: "boiler-suit",
      displayName: "Boiler Suit",
    },
    {
      id: "gid://shopify/TaxonomyValue/24762",
      handle: "catsuit",
      displayName: "Catsuit",
    },
    {
      id: "gid://shopify/TaxonomyValue/24763",
      handle: "coverall",
      displayName: "Coverall",
    },
    {
      id: "gid://shopify/TaxonomyValue/24764",
      handle: "dungaree",
      displayName: "Dungaree",
    },
    {
      id: "gid://shopify/TaxonomyValue/24765",
      handle: "jumpsuit",
      displayName: "Jumpsuit",
    },
    {
      id: "gid://shopify/TaxonomyValue/24766",
      handle: "leotard",
      displayName: "Leotard",
    },
    {
      id: "gid://shopify/TaxonomyValue/24767",
      handle: "overall",
      displayName: "Overall",
    },
    {
      id: "gid://shopify/TaxonomyValue/24768",
      handle: "playsuit",
      displayName: "Playsuit",
    },
    {
      id: "gid://shopify/TaxonomyValue/24769",
      handle: "romper",
      displayName: "Romper",
    },
    {
      id: "gid://shopify/TaxonomyValue/24770",
      handle: "salopette",
      displayName: "Salopette",
    },
    {
      id: "gid://shopify/TaxonomyValue/24771",
      handle: "unitard",
      displayName: "Unitard",
    },
    {
      id: "gid://shopify/TaxonomyValue/27928",
      handle: "other",
      displayName: "Other",
    },
  ],
};


export {mens_attributes, womens_attributes, features};